workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    max_build_duration: 120

    integrations:
      app_store_connect: ToyConnect

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gem.toy
      vars:
        UNITY_IOS_DIR: ios
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.gem.toy"
        APP_STORE_APPLE_ID: 6756122152

    scripts:
      - name: Download prepared Xcode project
        script: |
          echo "Downloading prepared Xcode project..."
          curl -L "https://drive.usercontent.google.com/download?id=1zG8C0uLhfT0mCP41ybIoWaSVIrVIFDjz&export=download&authuser=0&confirm=t&uuid=cdbf1ca2-bb04-4655-9870-f504178f913c&at=ALWLOp48RwP6QbKP6jyMSAiNpQVy%3A1765736532533" -o project.zip
          unzip -o project.zip -d ios

      - name: Fix code signing & Bitcode
        script: |
          cd $UNITY_IOS_DIR
          # Автоматическое применение профилей
          xcode-project use-profiles
        

      - name: Set version and build number
        script: |
          cd $UNITY_IOS_DIR
          # Важно: agvtool работает только внутри папки с проектом
          agvtool new-marketing-version 1.0
          agvtool new-version -all 1
      
      - name: Build the project
        script: |
          # Явно заходим в папку перед билдом
          cd $UNITY_IOS_DIR
          
          # Восстанавливаем права на всякий случай тут тоже
          find . -type f -name "MapFileParser" -exec chmod +x {} \;
          
          echo "Starting Raw xcodebuild..."
          
          # Запускаем напрямую xcodebuild. Если упадет, мы увидим реальную причину в консоли.
          xcodebuild -workspace "Unity-iPhone.xcworkspace" \
            -scheme "Unity-iPhone" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            archive \
            -archivePath "build.xcarchive" \
            CODE_SIGN_STYLE="Manual" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM="ZBXQD67DFW" \
            PROVISIONING_PROFILE_SPECIFIER="sloygem" \
            ENABLE_BITCODE=NO
             # Проверяем статус. Если pipefail сработал, $? вернет код ошибки xcode-project
             BUILD_STATUS=$?
             
             if [ $BUILD_STATUS -ne 0 ]; then
               echo "❌ Build failed with exit code $BUILD_STATUS"
               echo "📜 Dumping last 500 lines of logs for debugging:"
               echo "========================================================"
            
               # Выводим хвост лога (последние 500 строк)
               tail -n 500 xcode_build.log
            
               echo "========================================================"
               exit $BUILD_STATUS
             fi
        
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
