workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    max_build_duration: 120

    integrations:
      app_store_connect: ToyConnect

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gem.toy
      vars:
        UNITY_IOS_DIR: ios/build
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.gem.toy"
        APP_STORE_APPLE_ID: 6756122152

    scripts:
      - name: Download prepared Xcode project
        script: |
          set -euo pipefail
          echo "Downloading prepared Xcode project..."
          curl -L "https://drive.usercontent.google.com/download?id=1xTHeRe5xmxHHO_Wh3IeCQ8C7j0-YXp3k&export=download&authuser=0&confirm=t&uuid=4a57c2de-252c-4e9b-8774-e571bb4453a4&at=ANTm3cxDAKh-hGChUtFjHJYvnT0j%3A1768463359854" -o project.zip
          unzip -o project.zip -d ios

          # Если распакованный проект оказался не в ios/build, переместим его
          if [ ! -d "ios/build" ]; then
            echo "ios/build not found after unzip, attempting to locate Unity-iPhone project..."
            if [ -f "ios/Unity-iPhone.xcworkspace/contents.xcworkspacedata" ] || [ -d "ios/Unity-iPhone.xcodeproj" ]; then
              mkdir -p ios/build
              rsync -a --delete --exclude "__MACOSX" ios/ ios/build/
            fi
          fi

          echo "AppLocalization files in extracted archive:"
          find ios/build/AppLocalization -maxdepth 3 -type f -print || true

      - name: Normalize project paths (remove absolute AppLocalization refs)
        script: |
          set -euo pipefail
          cd "$UNITY_IOS_DIR"
          PROJECT_PBXPROJ="Unity-iPhone.xcodeproj/project.pbxproj"

          if [ ! -f "$PROJECT_PBXPROJ" ]; then
            echo "project.pbxproj not found at $PROJECT_PBXPROJ"
            exit 1
          fi

          echo "Before fix: absolute AppLocalization references:"
          grep -nE "/Users/.*/AppLocalization/|/Volumes/.*/AppLocalization/|sourceTree = \"<absolute>\"" "$PROJECT_PBXPROJ" || true

          TMP_FILE="$(mktemp)"

          # Важно: делаем замены максимально универсальными
          sed -E '
            # Любые абсолютные пути на macOS к AppLocalization -> относительный путь
            s#/Users/[^;]*/AppLocalization/#AppLocalization/#g;
            s#/Volumes/[^;]*/AppLocalization/#AppLocalization/#g;

            # Старый кейс: .../build/AppLocalization/... -> AppLocalization/...
            s#/Users/[^;]*/build/AppLocalization/#AppLocalization/#g;

            # Иногда встречается относительный build/AppLocalization
            s#([^A-Za-z0-9_])/build/AppLocalization/#\1AppLocalization/#g;

            # Починить sourceTree если Xcode пометил как absolute
            s#sourceTree = \"<absolute>\";#sourceTree = \"<group>\";#g
          ' "$PROJECT_PBXPROJ" > "$TMP_FILE"
          mv "$TMP_FILE" "$PROJECT_PBXPROJ"

          echo "After fix: remaining absolute AppLocalization references (should be none):"
          if grep -nE "/Users/.*/AppLocalization/|/Volumes/.*/AppLocalization/" "$PROJECT_PBXPROJ"; then
            echo "ERROR: Some absolute AppLocalization paths still remain in project.pbxproj"
            exit 1
          else
            echo "OK: no absolute AppLocalization paths remain"
          fi

          # Проверка наличия локализованных файлов в рабочей директории проекта
          test -f AppLocalization/en.lproj/Localizable.strings || { echo "Missing AppLocalization/en.lproj/Localizable.strings"; exit 1; }
          test -f AppLocalization/en.lproj/InfoPlist.strings || { echo "Missing AppLocalization/en.lproj/InfoPlist.strings"; exit 1; }

      - name: Fix CocoaPods script permissions
        script: |
          set -euo pipefail
          cd "$UNITY_IOS_DIR"

          if [ -d "Pods" ]; then
            echo "Fixing executable permissions for *.sh in Pods..."
            find "Pods" -type f -name "*.sh" -print -exec chmod +x {} \;
          fi

          # Диагностика для AppsFlyer
          if [ -f "Pods/Target Support Files/AppsFlyerFramework/AppsFlyerFramework-xcframeworks.sh" ]; then
            ls -la "Pods/Target Support Files/AppsFlyerFramework/AppsFlyerFramework-xcframeworks.sh"
          fi

      - name: Clean DerivedData and ModuleCache
        script: |
          set -euo pipefail
          rm -rf "$HOME/Library/Developer/Xcode/DerivedData"
          rm -rf "$HOME/Library/Developer/Xcode/ModuleCache.noindex"
          echo "DerivedData + ModuleCache cleaned"

      - name: Fix code signing
        script: |
          set -euo pipefail
          cd "$UNITY_IOS_DIR"
          xcode-project use-profiles

      - name: Set version and build number
        script: |
          set -euo pipefail
          cd "$UNITY_IOS_DIR"
          agvtool new-marketing-version 1.2
          agvtool new-version -all 3

      - name: Build the project (IPA)
        script: |
          set -euo pipefail
          cd "$UNITY_IOS_DIR"

          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --verbose 2>&1 | tee xcode_build.log

          echo "Listing exported IPAs from build/ios/ipa:"
          ls -la build/ios/ipa

          mkdir -p ../../ipa_out
          cp -f build/ios/ipa/*.ipa ../../ipa_out/
          echo "Listing IPA in ipa_out:"
          ls -la ../../ipa_out

    artifacts:
      - ios/build/xcode_build.log
      - ios/build/build/ios/ipa/*.ipa
      - ipa_out/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
