workflows:
  ios-build:
    name: iOS Build from Google Drive
    environment:
      xcode: latest
      vars:
        GDRIVE_FILE_ID: "ВАШ_ID_ФАЙЛА"   # ID архива проекта в Google Drive
    scripts:
      - name: Download project from Google Drive
        script: |
          echo "Downloading project archive..."
          curl -L "https://drive.google.com/uc?export=download&id=$GDRIVE_FILE_ID" -o project.zip
          unzip -o project.zip -d project
