workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    max_build_duration: 120

    integrations:
      app_store_connect: ToyConnect   # интеграция из Team settings

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gem.toy
      vars:
        UNITY_IOS_DIR: ios
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.gem.toy"
        APP_STORE_APPLE_ID: 6756122152

    scripts:
      - name: Download prepared Xcode project from Google Drive
        script: |
          echo "Downloading prepared Xcode project..."
          curl -L "https://drive.usercontent.google.com/download?id=14QS8H_nbzd8dS5tcDlYPBFh63VJq9kb8&export=download&authuser=0&confirm=t&uuid=ff1451ae-1304-44a4-aec0-2b27ac609334&at=ALWLOp7FpB8iR1cvM6qRbz8bZOv_%3A1765481145262" -o project.zip
          unzip -o project.zip -d ios
          echo "Contents of ios directory:"
          ls -R ios

      - name: Fix code signing settings
        script: |
          cd $UNITY_IOS_DIR
          xcode-project use-profiles

      - name: Patch UnityFramework build settings
        script: |
          cd $UNITY_IOS_DIR
          # Включаем поддержку модулей и определение модуля
          sed -i '' 's/CLANG_ENABLE_MODULES = NO/CLANG_ENABLE_MODULES = YES/g' Unity-iPhone.xcodeproj/project.pbxproj || true
          sed -i '' 's/DEFINES_MODULE = NO/DEFINES_MODULE = YES/g' Unity-iPhone.xcodeproj/project.pbxproj || true
          # Убираем жёсткий Werror
          sed -i '' 's/-Werror=non-modular-include-in-framework-module//g' Unity-iPhone.xcodeproj/project.pbxproj || true
          echo "Patched UnityFramework: modules enabled, DEFINES_MODULE set, Werror removed"

      - name: Set version and build number
        script: |
          cd $UNITY_IOS_DIR
          agvtool new-marketing-version 1.0
          agvtool new-version -all 1
          echo "Version set to 1.0, build number set to 1"

      - name: Build the project
        script: |
          xcode-project build-ipa \
            --project "ios/Unity-iPhone.xcodeproj" \
            --scheme "$XCODE_SCHEME" \
            --archive-xcargs "COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGN_STYLE=Manual"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
