workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    max_build_duration: 120

    integrations:
      app_store_connect: ToyConnect

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gem.toy
      vars:
        UNITY_IOS_DIR: ios
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.gem.toy"
        APP_STORE_APPLE_ID: 6756122152

    scripts:
      - name: Download prepared Xcode project
        script: |
          echo "Downloading prepared Xcode project..."
          curl -L "https://drive.usercontent.google.com/download?id=1ikmoDGkkl8kf-c7DiLhTcXvSgMy0BdIv&export=download&authuser=0&confirm=t&uuid=8a3072d0-a1a0-47fe-944b-94b28e38d7e0&at=ALWLOp5w_SdhYu-YjlKPHTYRRJuL%3A1765802775369" -o project.zip
          unzip -o project.zip -d ios

      - name: Install CocoaPods
        script: |
          cd $UNITY_IOS_DIR
          if [ -f "Podfile" ]; then
            echo "Updating pod specs and installing pods..."
            pod repo update
            pod install --repo-update
          else
            echo "No Podfile found, skipping CocoaPods installation."
          fi

      - name: Fix code signing & Bitcode
        script: |
          cd $UNITY_IOS_DIR
          # Автоматическое применение профилей
          xcode-project use-profiles
        

      - name: Set version and build number
        script: |
          cd $UNITY_IOS_DIR
          # Важно: agvtool работает только внутри папки с проектом
          agvtool new-marketing-version 1.0
          agvtool new-version -all 1
      
      - name: Build the project
        script: |
          # Явно заходим в папку перед билдом
          cd $UNITY_IOS_DIR
          
          # Запуск сборки
          xcode-project build-ipa \
             --workspace "Unity-iPhone.xcworkspace" \
             --scheme "$XCODE_SCHEME" \
             --xcargs "ENABLE_USER_SCRIPT_SANDBOXING=YES COMPILER_INDEX_STORE_ENABLE=NO" \
             --verbose 2>&1 | tee xcode_build.log

             
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
