workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    max_build_duration: 120

    integrations:
      app_store_connect: ToyConnect

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gem.toy
      vars:
        UNITY_IOS_DIR: ios/build
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.gem.toy"
        APP_STORE_APPLE_ID: 6756122152

    scripts:
      - name: Download prepared Xcode project
        script: |
          echo "Downloading prepared Xcode project..."
          curl -L "https://drive.usercontent.google.com/download?id=1pPchjC-OZySHkkm9pib3FnQGsrVi_cZL&export=download&authuser=0&confirm=t&uuid=69e76f13-1b30-4313-b17d-99fa7f468a3a&at=ANTm3cxQ5kW3A-qmJ19SU_M4rozP%3A1767035247868" -o project.zip
          unzip -o project.zip -d ios

          # Если распакованный проект оказался не в ios/build, переместим его (адаптируйте под фактический путь из архива):
          if [ ! -d "ios/build" ]; then
            echo "ios/build not found after unzip, attempting to locate Unity-iPhone project..."
            if [ -f "ios/Unity-iPhone.xcworkspace/contents.xcworkspacedata" ] || [ -d "ios/Unity-iPhone.xcodeproj" ]; then
              mkdir -p ios/build
              rsync -a --delete --exclude "__MACOSX" ios/ ios/build/
            fi
          fi
          echo "Tree under ios/build:"
          find ios/build -maxdepth 3 -type f -print | sed 's#^#  #'

      - name: Normalize project paths
        script: |
          set -euo pipefail
          cd "$UNITY_IOS_DIR"
          PROJECT_PBXPROJ="Unity-iPhone.xcodeproj/project.pbxproj"

          if [ -f "$PROJECT_PBXPROJ" ]; then
            echo "Before fix - absolute references (preview):"
            grep -nE "/Users/|sourceTree = \"<absolute>\"" "$PROJECT_PBXPROJ" || true

            TMP_FILE="$(mktemp)"
            sed -E '
              s#/Users/[^;]*/build/AppLocalization/#AppLocalization/#g;
              s#([^A-Za-z0-9_])/build/AppLocalization/#\1AppLocalization/#g;
              s#sourceTree = \"<absolute>\";#sourceTree = \"<group>\";#g
            ' "$PROJECT_PBXPROJ" > "$TMP_FILE"
            mv "$TMP_FILE" "$PROJECT_PBXPROJ"

            echo "After fix - absolute references (preview):"
            grep -nE "/Users/|sourceTree = \"<absolute>\"" "$PROJECT_PBXPROJ" || echo "OK: no absolute paths remain"
          else
            echo "project.pbxproj not found at $PROJECT_PBXPROJ"
          fi

          # Быстрая проверка наличия локализованных файлов
          test -f AppLocalization/en.lproj/Localizable.strings || { echo "Missing AppLocalization/en.lproj/Localizable.strings"; exit 1; }
          test -f AppLocalization/en.lproj/InfoPlist.strings || { echo "Missing AppLocalization/en.lproj/InfoPlist.strings"; exit 1; }

      - name: Clean DerivedData
        script: |
          rm -rf "$HOME/Library/Developer/Xcode/DerivedData"
          echo "DerivedData cleaned"

      - name: Fix code signing & Bitcode
        script: |
          cd "$UNITY_IOS_DIR"
          xcode-project use-profiles

      - name: Set version and build number
        script: |
          cd "$UNITY_IOS_DIR"
          agvtool new-marketing-version 1.1
          agvtool new-version -all 2

      - name: Build the project
        script: |
          cd "$UNITY_IOS_DIR"
          xcode-project build-ipa \
             --workspace "$XCODE_WORKSPACE" \
             --scheme "$XCODE_SCHEME" \
             --verbose 2>&1 | tee xcode_build.log

          echo "Listing exported IPAs from build/ios/ipa:"
          ls -la build/ios/ipa || true

          mkdir -p ../../ipa_out
          cp -f build/ios/ipa/*.ipa ../../ipa_out/ || { echo "IPA not found after export"; exit 1; }
          echo "Listing IPA in ipa_out:"
          ls -la ../../ipa_out

    artifacts:
      - build/ios/ipa/*.ipa
      - ipa_out/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
