workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    max_build_duration: 120

    integrations:
      app_store_connect: ToyConnect

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gem.toy
      vars:
        UNITY_IOS_DIR: ios
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.gem.toy"
        APP_STORE_APPLE_ID: 6756122152

    scripts:
      - name: Download prepared Xcode project from Google Drive
        script: |
          echo "Downloading prepared Xcode project..."
          curl -L "https://drive.usercontent.google.com/download?id=1CB2XYBxh_2J918idztblFatjNTP1ZpkX&export=download&authuser=0&confirm=t&uuid=3073ff61-3bb2-4570-8ea4-8ef58428adc6&at=ALWLOp77IDN_dwpph-LDcdijZn49%3A1765455131366" -o project.zip
          unzip -o project.zip -d ios
          echo "Contents of ios directory:"
          ls -R ios

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build the project
        script: |
          xcode-project build-ipa \
            --project "ios/Unity-iPhone.xcodeproj"
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
     
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: true
