workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    max_build_duration: 120

    integrations:
      app_store_connect: ToyConnect   # интеграция из Team settings

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gem.toy
      vars:
        UNITY_IOS_DIR: ios
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.gem.toy"
        APP_STORE_APPLE_ID: 6756122152

    scripts:
      - name: Download prepared Xcode project from Google Drive
        script: |
          echo "Downloading prepared Xcode project..."
          curl -L "https://drive.usercontent.google.com/download?id=1FN9Ujv3sHHZEUjimBpbDhNUgTgY04fB0&export=download&authuser=0&confirm=t&uuid=b642c38e-be3a-4b93-9c76-40d43e988b6c&at=ALWLOp75FGQ8shwEW8IGuYa-RWfg%3A1765722283232" -o project.zip
          unzip -o project.zip -d ios
          echo "Contents of ios directory:"
          ls -R ios

      - name: Fix code signing settings
        script: |
          cd $UNITY_IOS_DIR
          xcode-project use-profiles
         
      - name: Set version and build number
        script: |
          cd $UNITY_IOS_DIR
          agvtool new-marketing-version 1.0
          agvtool new-version -all 1
          echo "Version set to 1.0, build number set to 1"
      
      - name: Build the project
        script: |
          xcode-project build-ipa \
          --workspace "ios/Unity-iPhone.xcworkspace" \
          --scheme "$XCODE_SCHEME" \
        
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
